### PR TITLE
Add code for inference

### PR DESCRIPTION
**Pull request by h-s-dev**
# Added code
I have added a new inference script, infer.py.
Additionally, I have added a dataset class for inference purposes (MVTecDatasetInfer).

# reading and writing faiss indices
```
class PatchCore:

    def save_neighbor(self, type_data):
        faiss_save_path = os.path.join(self.faiss_save_dir, f'{type_data}.idx')
        cpu_index = faiss.index_gpu_to_cpu(self.index_feat)
        faiss.write_index(cpu_index, faiss_save_path)

    def load_neighbor(self, type_data):
        faiss_idx_path = os.path.join(self.faiss_save_dir, f'{type_data}.idx')
        self.index_feat = faiss.read_index(faiss_idx_path)
```

save code
```
def apply_patchcore(args, type_data, feat_ext, patchcore, cfg_draw):
    patchcore.save_neighbor(type_data)
```

load code
```
def apply_patchcore(args, type_data, feat_ext, patchcore, cfg_draw):
    patchcore.load_neighbor(type_data)

```

The location of the faiss index is specified below.
```
parser.add_argument('--faiss_save_dir', type=str, default='output', help='Specify the directory to output faiss index')
```

# Storing thresholds for inference
Modified to automatically calculate thresholds to determine if an image is an anomalous image and store them for inference.

The storage location is specified below
```
    parser.add_argument('--thr_save_dir', type=str, default='output', help='Specify the directory to output img thresholds')
```

# Output of inference results
The result will be output as shown in the figure below.
image

The output location is specified below
```
    parser.add_argument('-pr', '--path_result', type=str, default='./result',
```

### CODE REVIEW

**Comment by h-s-dev** [comment]
# Visualization of inference results
If --verbose is set, the inference is visualized and output to the directory set in --path_result.

(ex)
localization_bottle_broken_large_000_p0010_k05_s067_infer
localization_cable_bent_wire_000_p0010_k05_s077

**Comment by h-s-dev** [comment]
# WIP

localization_bottle_broken_large_000_p0010_k05_s067

localization_bottle_broken_large_000_p0010_k05_s069

**Comment by h-s-dev** [comment]
# Visualization of Patch
The modification has been made to enable visualization of patches just like during training.

| train | infer |
|---------|--------|
|localization_bottle_broken_large_001_p0010_k05_s068 | localization_bottle_broken_large_001_p0010_k05_s068 |
| localization_cable_bent_wire_000_p0010_k05_s079 | localization_cable_bent_wire_000_p0010_k05_s079 |

I have made changes to save the following during training so that patches can be visualized during inference as well.
- all patch images 
(ex) bottle_coreset_patch_img.npy
- all patch index
(ex) bottle_coreset_patch_idx.npy

The location to save the above is specified during training with the ```--coreset_patch_save_dir``` option.

To load the saved patch images and patch index during inference, specify with the ```--coreset_patch_save_dir``` option, similar to the above.

localization_bottle_broken_large_000_p0010_k05_s156

**Comment by h-s-dev** [comment]
# train and infer on cpu

If --cpu is specified, train and infer can be performed with cpu only.

The main modifications are as follows
```
class FeatExtract:
        code = 'self.backbone = %s(weights=%s)' % (cfg_feat.backbone, cfg_feat.weight)
        exec(code)
        summary(self.backbone, input_size=(1, 3, *self.shape_input))
        self.backbone.eval()

        # Executing summary will force the backbone device to be changed to cuda, so do to(device) after summary
        self.backbone.to(self.device)
```

It appears that summary method internally sets the cuda to the model(PyTorch 2.1.0).
So I moved self.backbone.to(self.device) to after summary.

Also, for cpu, change the index of faiss as follows
```
class PatchCore:
        if self.device.type != 'cuda':
            self.index_feat = faiss.IndexFlatL2(self.dim_coreset_feat)
        else:
            self.index_feat = faiss.GpuIndexFlatL2(faiss.StandardGpuResources(),
                                                   self.dim_coreset_feat,
                                                   faiss.GpuIndexFlatConfig())

```

**Comment by h-s-dev** [comment]
# Inference from video

Specify the video to be inferred with --path_input_video.
Specify the file that contains the faiss index with --faiss_index_path.

```
python infer_by_video.py \
--path_parent=/ssd/dev/dataset/mvtec \
--path_input_video=../../dataset/video/bottle_simple.mp4 \
--faiss_index_path=output/bottle.idx 
```

Below is an example of inferring a video

https://github.com/any-tech/PatchCore-ex/assets/21982866/bb1ce2a2-2867-45a0-8503-9e8615188cfe

https://github.com/any-tech/PatchCore-ex/assets/21982866/7e3171c4-1601-4d95-81af-c8d2b9790e89

**Comment by h-s-dev** [comment]
More command line options
--mode_visualize=infer is fixed.
--path_coreset_patch_img specifies the file where img patch is saved.
If --display_video is specified, you can see a movie of inference in progress.

```
python infer_by_video.py \
--path_parent=/ssd/dev/dataset/mvtec \
--path_input_video=../../dataset/video/bottle_simple.mp4 \
--faiss_index_path=output/bottle.idx  \
--path_coreset_patch_img=output/bottle_coreset_patch_img.npy \
--mode_visualize=infer \
--display_video
```

**Comment by h-s-dev** [comment]
# layer weights option
It is possible to change the weight of each layer by specifying the following

```
--layer_weights
0.01
0.99
```
| layer2: 1.0, layer3: 1.0 | layer2: 0.01, layer3: 0.99 |
|--------------------------|----------------------------|
| localization_bottle_broken_large_000_p0010_k05_s068 | localization_bottle_broken_large_000_p0010_k05_s051 |

**Review by mucunwuxian — APPROVED** [review]

**Comment by mucunwuxian** [comment]
@h-s-dev 
Thank you for your implementing! :-D

**Pull request merged**
